### ISSUE TITLE
Pictures not displaying on site

### ISSUE THREAD

**Issue by mariobehling** [fossasia/2023.fossasia.org#1]

**Comment by namangoel1** [comment]
I was able to fix some of those by updating the ImageCache module. I've set to upload all images from the old server, I hope it works. Strange error, and difficult to debug since the admin area is in another language (Bahasa Indonesian it seems)

**Comment by namangoel1** [comment]
Seems that the upload does the trick.

**Comment by mariobehling** [comment]
Ok, let's see. To get the admin area in English go to the start page and click "English" on the top left. You will then get to http://libregraphics.asia/en/ and everything will be in English.

**Comment by tradzik** [comment]
@mariobehling Sorry for off-topic, but I want to raise your attention on
this issue: https://github.com/fossasia/fossasia10/issues/47 I would be
nice, if you answer me. Additionally I see you're working with Namanyay on
some new repos in FOSSASIA Github. Can I help you in something there?

Sat Jan 24 2015 at 22:01:58 użytkownik mariobehling <
notifications@github.com> napisał:

**Comment by mariobehling** [comment]
Gallery not working yet: http://libregraphics.asia/en/gallery

**Comment by mariobehling** [comment]
@ty221 Images are not displayed. Are you interested to help out?

**Comment by tradzik** [comment]
@mariobehling Yes, I am glad I have possibility to help. Please contact me giving server login data

**Comment by tradzik** [comment]
That's was a problem with URLs caching. Fixed. Closing...
